#node exporter uses prometheus to pull metric data. Run it using docker.
#use grafana node exporter full dashboard to visualize the metric data.

apiVersion: apps/v1
kind: DeamonSet
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    name: node-exporter
spec:
  selector:
    matchLabels: 
      name: node-exporter
  template:
    metadata:
    labels:
    name: node-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9100"
  spec:
    hostPID: true 
    hostIPC: true 
    hostNetwork: true 
    containers:
      - ports:
        - containerPort: 9100
          protocol: TCP
        resources:
          requests:
            cpu: 0.15
        securityContext:
         privileged: true
        image: prom/node-exporter:v1.6.0
        args:
          - --path.procfs
          - /host/proc
          - --path.sysfs
          - /host/sys
          - --collector.filesystem.ignored-mount-points
          - '"^/(sys|proc|dev|host|etc)($|/)"'
        name: node-exporter
        volumeMounts:
          - name: dev
            mountPath: /host/dev
          - name: proc
            mountPath: /host/proc
          - name: sys 
            mountPath: /host/sys
          - name: rootfs
            mountPath: /rootfs
    volumes:
      - name: proc
        hostPath: 
          path: /proc
      - name: dev
        hostPath:
          path: /dev
      - name: sys 
        hostPath: 
        path: /sys
      - name: rootfs
        hostPath: 
        path: /